ens_jobeet_ens_job:
    resource: "@EnsJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /ens_job

ens_jobeet_homepage:
    path:     /
    defaults: { _controller: EnsJobeetBundle:Job:index }

EnsJobeetBundle_category:
    path:  /category/{slug}/{page}
    defaults: { _controller: EnsJobeetBundle:Category:show, page: 1 }

login:
    path:   /login
    defaults:  { _controller: EnsJobeetBundle:Default:login }

login_check:
    path:   /login_check

logout:
    path:   /logout