security:
    encoders:
            Ens\JobeetBundle\Entity\User:
                algorithm: bcrypt

    providers:

            db_provider:
                entity:
                    class: Ens\JobeetBundle\Entity\User
                    property: username

    firewalls:
        main:
            pattern:    ^/
            provider: db_provider
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
